baseURL = "http://lunafromthemoon.github.io/RenJS"
languageCode = "en-us"
title = "RenJS"
# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionnality
[outputs]
home = [ "HTML", "RSS", "JSON"]

